workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    working_directory: client
    environment:
      flutter: default
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Flutter build ios (unsigned)
        script: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          zip -r Livriyes_iOS_Unsigned.zip Runner.app
    artifacts:
      - build/ios/iphoneos/*.zip
      - /tmp/xcodebuild_logs/*.log
